import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home({ data }) {
  const [users, setUsers] = useState(data);
  const [sortOrder, setSortOrder] = useState('asc');

  const sortUsersByKey = (key) => {
    let sortedUsers = [...users]
    sortedUsers.sort((a, b) => {
      if(a[key] > b[key]) return sortOrder === 'asc' ? 1 : -1
      if(a[key] < b[key]) return sortOrder === 'asc' ? -1 : 1
      return 0
    })
    setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc')
    setUsers(sortedUsers)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Test Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">Users list</div>
        <table>
          <tbody>
            <tr>
              <th><button onClick={() => sortUsersByKey('id')}>Id</button></th>
              <th><button onClick={() => sortUsersByKey('name')}>Name</button></th>
              <th><button onClick={() => sortUsersByKey('username')}>Username</button></th>
              <th><button onClick={() => sortUsersByKey('email')}>Email</button></th>
              <th><button onClick={() => sortUsersByKey('phone')}>Phone</button></th>
            </tr>
            {users && users.map(user => (
              <tr key={user.id}>
                <td>{user.id}</td>
                <td>{user.name}</td>
                <td>{user.username}</td>
                <td>{user.email}</td>
                <td>{user.phone}</td>
              </tr>
            ))}
          </tbody>
        </table>
    </div>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users')
  const data = (await res.json());
  return { props: { data } }
}
