import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home({ data }) {
  const [users, setUsers] = useState(data);
  const [sortOrder, setSortOrder] = useState('asc');

  const headers = [
    { key: 'id', title: 'Id' },
    { key: 'name', title: 'Name' },
    { key: 'username', title: 'Username' },
    { key: 'email', title: 'Email' },
    { key: 'phone', title: 'Phone' },
  ]

  const sortUsersByKey = (key) => {
    let sortedUsers = [...users]
    sortedUsers.sort((a, b) => {
      if (a[key] > b[key]) return sortOrder === 'asc' ? 1 : -1
      if (a[key] < b[key]) return sortOrder === 'asc' ? -1 : 1
      return 0
    })
    setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc')
    setUsers(sortedUsers)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Test Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">Users list</div>
      <table>
        <tbody>
          <tr>
            {headers.map(({ key, title }) => (
              <th key={key}><button onClick={() => sortUsersByKey(key)}>{title}</button></th>
            ))}
          </tr>
          {users && users.map(user => (
            <tr key={user.id}>
              <td>{user.id}</td>
              <td>{user.name}</td>
              <td>{user.username}</td>
              <td>{user.email}</td>
              <td>{user.phone}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users')
  const data = (await res.json());
  return { props: { data } }
}
